debian/postinst
Prevents error messages in postinst which result in errors on package install/upgrade.
=> Manipulates log files only if they exist.

debian/init.d, debian/postinst
Just like the videobridge, allow the user to specify additional configuration options to jigasi. For example specify a different port range.
=> Add $JIGASI_OPTS variable to the init.d and config files.

debian/postinst
During postinstall jigasi replaces the call control value in the jitsi-meet config. But depending on the jitsi-meet config it may break the JSON format, due to the missing colon and the end o f the line.
=> Fix missing colon in sed call_control replace.

src/main/java/org/jitsi/jigasi/AbstractGateway.java, src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/GatewayListener.java, src/main/java/org/jitsi/jigasi/GatewaySessionListener.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGateway.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/rest/HandlerImpl.java, src/main/java/org/jitsi/jigasi/rest/Statistics.java, src/main/java/org/jitsi/jigasi/xmpp/CallControl.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java, src/test/java/org/jitsi/jigasi/CallsHandlingTest.java, src/test/java/org/jitsi/jigasi/GatewaySessionAsserts.java
This pr splits up Sipgateway into an AbstractGateway which is now extended by SipGateway.
The same happened to GatewaySession, creating an AbstractGatewaySession which only has code regarding joining a conference and SipgatewaySession, which is the old GatewaySession.
Due to these changes the SipGatewayListener and GatewaySessionListener have been modified to now
listen for the abstract versions. 
Includes minor changes in other classes (mainly changes types to SipGatewaySession)
Also adds a notification for members leaving a conference (from JvbConference to AbstractGatewaySession)
=> refactor of GatewaySession and SipGateway

pom.xml, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java, src/main/java/org/jitsi/jigasi/transcription/TranscribingAudioMixerMediaDevice.java, src/main/java/org/jitsi/jigasi/transcription/Transcription.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionListener.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionRequest.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionResult.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionService.java
This PR relies on[ RawStreamListener from libjitsi](https://github.com/nikvaessen/libjitsi/tree/RawStreamListener)
=> add initial transcription module, set language level to 1.8, add GoogleCloudTranscriptionService

src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
This allows the TranscriptionGatewaySession to still work when the following properties are set in sip-communicator.properties:
net.java.sip.communicator.impl.neomedia.audioSystem.audiosilence.captureDevice_list=["AudioSilenceCaptureDevice:noTransferData"]
org.jitsi.jigasi.xmpp.acc.USE_TRANSLATOR_IN_CONFERENCE=true
=> add check for XMPP translator support and overwrite property when it is not supported by a GatewaySession

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
We closed a session when Google send an END_OF_SINGLE_UTTERANCE event, which
was received before the final result came in. This resulted in the
JSON object with the final result getting a new message ID.
This commit fixed this issue by making a new ResponseObserver
for each session, where each ResponseObserver has its own
unique ID
=> Fix a bug regarding messageID's and interim results

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
Sometimes when the transcriber joins a room, there are warnings for audio which cannot be linked to a name due to unknown SSRC. This has yet to occur after these changes.
=> potentially fix dealing with audio from unknown SSRC

pom.xml
Seems the problem is using an older(2.0.0) whack version, while jicoco uses 2.0.1. This should fix it, although I don't see to be fixed locally. I keep seeing that it depends: org.jitsi:jicoco:jar:1.1-SNAPSHOT:compile which depends on whack 2.0.0. But anyway whack should be coming with jicoco and should not be declared in jigasi.
=> Leave whack version to come from jicoco dependency.

src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
This PR disables the 'initialising call' presence update when the Transcriber joins a conference.
=> disable 'initialising call' when transcriber joins

pom.xml, src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java, src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/RemotePublisherTranscriptionHandler.java
Relies on PR [jitsi/jitsi#495](https://github.com/jitsi/jitsi/pull/495)
=> Uses json message extension for publishing json transcripts. 

jigasi-home/sip-communicator.properties, pom.xml, src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranslationService.java, src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/LocalTxtTranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/Participant.java, src/main/java/org/jitsi/jigasi/transcription/RemotePublisherTranscriptionHandler.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/TranslationManager.java, src/main/java/org/jitsi/jigasi/transcription/TranslationResult.java, src/main/java/org/jitsi/jigasi/transcription/TranslationResultListener.java, src/main/java/org/jitsi/jigasi/transcription/TranslationService.java, src/main/java/org/jitsi/jigasi/transcription/action/ActionServicesHandler.java
Depends on 
Can be tested by dialing the transcriber and setting the language from console : 
`APP.conference._room.setLocalParticipantProperty('translation_language','hi');`
=> Sends json-messages for translations & Sets the participant translation language on presence update

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
Source language can be set by : 
`APP.conference._room.setLocalParticipantProperty('transcription_language','hi-IN');`
=> Sets source language for transcription with presence update

pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java
Few fixes for exceptions I saw during testing.
Fixes memory leak, leaking and not disconnecting bosh connections. I still see the nginx server timeout, but it is very rear and I still see it on the muc control connection, which reconnects maybe some timing need to be tuned.
I was reproducing 10-20% of the times not working transcription, moving the setConference call earlier (before answering the call) fixes it for me.
Sometimes I was seeing the conference to timeout, and this was because kick of the transcription participant was not detected in the code. Sometimes the listener for the kick is invoked and sometimes the participant leave one by one and we were not detecting correctly that the focus has left.
=> Few improvements.

pom.xml
Can successfully disable jingle-nodes which leaks connections. Disables
port tracker ot increase ports without checking range, which can lead to
healthchecks failing. Fixes setting keep-alive interval for xmpp
accounts.
=> Updates jitsi dependency to 2.13.4056694.

src/main/java/org/jitsi/jigasi/health/SipHealthPeriodicChecker.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Avoids reusing the same nickname.
=> Use the connection resource as nickname when joining brewery room.

jigasi-home/sip-communicator.properties, pom.xml, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
Good news! The video model of the Google Cloud speech-to-text API can now be used. While it's more expensive to use, it also offers better transcription capabilities.
When this model was initially released in May 2018 it was not able to return IS_FINAL results. However, after trying to implement it again now it turns it is does return IS_FINAL results, making it possible to close the current StreamingSession and open a new one without having to do VAD ourselves.
=> Enable the use of better performing "video model" of Google Speech API

pom.xml, src/main/java/org/jitsi/jigasi/Main.java
Before merging, jitsi-desktop version needs to be updated after merging jitsi/jitsi#587
=> Update ScServiceDiscoveryManager to use smacks implementation.

pom.xml, src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/stats/Statistics.java
If we detect dropped media, print messages, add stats and when it
resumes stat is updated and message is printed that RTP resumed.
The setting is a threshold of time after which we consider media
for dropped, -1 disables the behaviour, default is 10 seconds and
enabled. There is also an option that, when enabled, calls can be
dropped when media stops.
=> Detects incoming media dropped on sip side.

pom.xml, src/main/java/org/jitsi/jigasi/stats/StatsHandler.java
Two changes:
- update to latest jitsi-stats to be able to indicate stats as for client (browser endpoint)
- get callstats config and from the client account props. This covers the case where there are no xmpp control accounts (dial out is disabled) and we still want to enable callstats.
=> Jigasi stats update

src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/stats/StatsHandler.java
Multiple calls in a conference were seen as one participant in callstats.io.
=> Updates stats to include originID as jigasi-number.

pom.xml
net.java.sip.communicator.impl.protocol.sip
.SKIP_REINVITE_ON_FOCUS_CHANGE_PROP, by default it is false.
=> Adds a global property to disable sip reinvites on focus changed.

build.xml, pom.xml, src/main/java/org/jitsi/jigasi/JigasiBundleActivator.java, src/main/java/org/jitsi/jigasi/osgi/JigasiBundleConfig.java, src/main/java/org/jitsi/jigasi/version/CurrentVersionImpl.java, src/main/java/org/jitsi/jigasi/version/VersionActivator.java
This adapts to the move of Version to jitsi-utils and uses its own implementation of a VersionService (extending the one in jicoco) instead of the one from jitsi-version. 
This will make jigasi identify itself as "Jigasi" to callstats.
=> Move version

src/main/java/org/jitsi/jigasi/CallContext.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/stats/Statistics.java
Throws stat when the XMPP part of the call receives connection failed
event. On connection fail the jingle call will be closed and room will
be left, waiting for connection to reconnect. When the connection
reconnects we join the room and new jingle call is established connected
to the sip one. When jingle call is hangup the invite timeout is
scheduled so this state of waiting to reconnect will finish either
successfully or when timeout is reached.
=> Allows reconnecting the XMPP part of the call in case of network errors.

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
Transcription was broken after the changes in
4d6b8bfaeff5d30a91c485ea11ad1d4e9e4710ab.
=> Fixes initiating transcriber.

pom.xml, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Updated jitsi-desktop dependency with changes where we can create
multiple accounts with the same USER_ID. Add some checks on whether accounts
already exist and add logs for easier debugging.
Adds ATLEAST_ONE_SUCCESSFUL_CONNECTION for new accounts as the server
maybe still in the process of spinning and we want to retry connecting
to it.
=> Updates dynamic control room configuration.

src/main/java/org/jitsi/jigasi/JvbConference.java
Found one Java-level deadlock:
=============================
"JvbInviteTimeout":
waiting to lock monitor 0x00007f014025f8b8 (object 0x000000070107ace8, a java.lang.Object),
which is held by "pool-13-thread-1"
"pool-13-thread-1":
waiting to lock monitor 0x00007f014025fcd8 (object 0x0000000701074568, a java.lang.Object),
which is held by "JvbInviteTimeout"
Java stack information for the threads listed above:
===================================================
"JvbInviteTimeout":
at org.jitsi.jigasi.JvbConference.setJvbCall(JvbConference.java:1396)
- waiting to lock <0x000000070107ace8> (a java.lang.Object)
at org.jitsi.jigasi.JvbConference.stop(JvbConference.java:514)
- locked <0x00000007010746a8> (a org.jitsi.jigasi.JvbConference)
at …
=> Fixes a deadlock where stop and JvbConfStopTimer sync in different order

pom.xml
If connection failed event and removing an account happen at the same
time, the thread for unregister&reconnect can put a PP instance in
currentlyReconnecting, while the provider is removed and we no longer
need to reconnect it.
=> Skips reconnecting removed providers.

src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGateway.java
In cases where there is no connection to the xmpp part we were logging
only `Incoming call received...` without any info for which call is this
and for which room we are trying to create an xmpp call.
=> Logs improvement on incoming sip call and jvb conference start.

src/main/java/org/jitsi/jigasi/transcription/Participant.java
Moves 'presence' null check into getTranscriptionRequestExtensionOrNull.
Changes Boolean.valueOf to Boolean.parseBoolean to avoid redundant Boolean boxing.
=> fix(Participant): NPE on this.chatMember

jigasi-home/sip-communicator.properties, pom.xml, src/main/java/org/jitsi/jigasi/CallManager.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/Main.java, src/main/java/org/jitsi/jigasi/rest/HandlerImpl.java, src/main/java/org/jitsi/jigasi/util/Util.java
This PR's goal was to minimize the synchronization in the reconnect logic, that we saw several times jigasi filing incoming calls because of some lock in the reconnect logic ... 
Needs updating the pom.xml after merging: https://github.com/jitsi/jitsi/pull/636 as this is the main change.
While testing several scenarios of reconnecting (restarting prosody and stopping in/out on port 443 on the server with iptables) fixed few other bugs like authenticated dynamic accounts not able reconnect.
=> Reconnect update

lib/logging.properties, src/main/java/org/jitsi/jigasi/JvbConference.java
Small fixes found while examing logs of running latest jigasi release and running the tests.
The tests fail from time to time because of async establishing calls. We need a listener to be notified when xmpp call was established in order to fix them.
=> Small fixes 

pom.xml
Fixes a lock we had seen where closing connection failed bosh connection
can cause a lock and then leak
https://github.com/igniterealtime/jbosh/pull/18
=> Updates jbosh to latest 0.9.2.

src/main/java/org/jitsi/jigasi/JvbConference.java
java.lang.NullPointerException
at org.jitsi.jigasi.JvbConference.setJvbCall(JvbConference.java:1437)
at org.jitsi.jigasi.JvbConference.stop(JvbConference.java:532)
at org.jitsi.jigasi.TranscriptionGatewaySession.lambda$notifyChatRoomMemberUpdated$0(TranscriptionGatewaySession.java:339)
at java.lang.Thread.run(Thread.java:748)
=> fix(JvbConference): NPE in setJvbCall

src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/SoundNotificationManager.java, src/main/java/org/jitsi/jigasi/util/Util.java
This PR should not change any logic, just extracts code dealing with the sound notifications played to the sip participant for recordings/live-streaming and max occupants and moves it in a separate class, so we can later add even more notifications and simplify the code in JvbConference and SipGatewaySession.
=> Introduces sound notification manager.

src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
Checks whether we have transcriptions request is by checking the last presence for that transcribe request extension in all participants.
MultiUserChat and ChatRoomJabberImpl both use StanzaListener for incoming Presence packets. It can happen (depending of listener order) that we first get the left event from MultiUserChat and then get the chance to update last presence, which cannot update it as member had left.
As a result we will have a participant which is offline, but it is lastPresence will say available and requesting transcription.
By removing the participant we make sure we don't fall in this case.
=> Clears participants instances on leave.

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/Participant.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java, src/main/java/org/jitsi/jigasi/transcription/Transcript.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionListener.java, src/main/java/org/jitsi/jigasi/transcription/TranslationManager.java
Will stop the transcription session if the GoogleCloudTranscriptionService comes back with ResourceExhaustedException.
Will also increment failed_transcriber Datadog property on failure.
=> feat(transcriptions): abort on quota limit reached

src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
The app is not expecting for that to happen also there is a known smack
issue which could lead to a deadlock:
https://discourse.igniterealtime.org/t/deadlock-between-the-reader-and-writer-with-stream-management/87442/3
=> fix(xmpp): disable stream management and resume

src/main/java/org/jitsi/jigasi/Main.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Seems that https://github.com/jitsi/jigasi/pull/258/commits/dfd269d33cb775b036649e6ef5cca9bf5ebd82d3 is not resolving the problem
and we still experience it.
While doing XMPPTCPConnection.setUseStreamManagementDefault we start
loading SmackInitialization class which waits for ProviderManager class
to be loaded but ProviderManager is waiting to load SmackInitialization.
Moving XMPPTCPConnection.setUseStreamManagementDefault in the main
thread will ensure we load SmackInitialization earlier and should fix
the problem.
=> Fix problem loading smack classes.

src/main/java/org/jitsi/jigasi/SipGateway.java
This adds a header that inform about the call direction and so get it available on xmpp leg.
Close #272
=> Add call direction header

src/main/java/org/jitsi/jigasi/JvbConference.java
In environment where jigasi cannot join room with password, fix to clear
listeners on failing to join the room.
=> fix: Clear listeners if we fail to join the room.

jigasi-home/sip-communicator.properties
Only enable this if necessary to debug, but not in default install.
The comment even says it disables it, but in previous setting it would (obviously) enable it.
=> Disable the pcap logging in default config

pom.xml, src/main/java/org/jitsi/jigasi/Main.java
Disabling Smack providers should happen before any Smack class loading
to prevent global/static connection listeners attaching.
This was causing several disco-info been executed on joining room that
slows down the connection.
This brings another optimization in smack to avoid muc service discovery
on every room joined, now it is done once every 24hours. https://github.com/jitsi/Smack/commit/4fa73bde03b27b9166809ca6c2e5ebafe7d844b7
=> fix: Disable Smack providers.

pom.xml, src/main/java/org/jitsi/jigasi/JigasiBundleActivator.java
The MediaPresenceExtension was getting overridden and some parts of the
jingle were not parsed.
The extension was a duplicate of SourcePacketExtension, so we got
removed it and started using the common one.
https://github.com/jitsi/jitsi/pull/696
=> fix: Fixes transcriber receiving conference member events.

README.md, src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java
=> Fix typo on comments and README

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
Currently final transcripts are discarded when unchanged from latest text,
which means they do not make it to the remote POST URL or to the final
saved transcript file.
=> GoogleCloudTranscription: save unchanged transcripts if they are final

src/main/java/org/jitsi/jigasi/AbstractGateway.java, src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/GatewaySessionListener.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/lobby/Lobby.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java, src/test/java/org/jitsi/jigasi/GatewaySessionAsserts.java
If the lobby is enabled in the room returns the lobby xmpp jid when trying to creat an outgoing call. UI can use this to auto-allow joining in the room.
=> fix: Updates around lobby and outgoing calls.

src/main/java/org/jitsi/jigasi/SipGatewaySession.java
The first init of StatsHandler is slow and we see errors like:
2021-01-08 18:22:32.033 INFO: [3575] org.jitsi.jigasi.SipGateway.incomingCallReceived().216 [ctx=16101301520322057628062] Incoming call received...
2021-01-08 18:22:32.076 INFO: [3575] org.jitsi.jigasi.stats.StatsHandler.getStatsServiceWrapper().276 [ctx=16101301520322057628062] Jitsi-stats library initializing for account: Jabber:jigasi@
2021-01-08 18:22:33.087 WARNING: [3577] org.jitsi.jigasi.SipGatewaySession.run().1745 [ctx=16101301520322057628062] No JVB room name provided in INVITE header
2021-01-08 18:22:33.102 INFO: [3579] org.jitsi.jigasi.SipGatewaySession.handleCallState().1616 [ctx=16101301520322057628062] SIP call ended: CallPeerChangeEvent: type=CallPeerStatusChange …
=> fix: Fixes NPE when stats are slow to init.

pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java
In case of jigasi we are announcing the ssrc that will be sent early in the jingle and we want to return the ssrc from the translator/rtpManager and that to be the only value (not the random from the AudioMediaStreamImpl or -1 from ).
=> fix: Uses correct ssrc for announcement and ssrc rewriting.

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
tested with google quick start sample codes for Chinese sentence and worked.
See https://cloud.google.com/speech-to-text/docs/languages
=> use language codes matching jitsi-meet interface config.

src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/stats/Statistics.java
In case of no activity we update the stats and drop the xmpp and sip call.
=> feat: Checks the jvb call for activity and drop on no media.

jigasi-home/sip-communicator.properties, src/main/java/org/jitsi/jigasi/JvbConference.java
I use jigasi in a special "mode" where after all web users have left, all jigasi calls need to be dropped automatically.
I'm proposing this change so that I don't have to build my own all the time but I'm not sure if it's acceptable by the jitsi community.
=> feat: drop jigasi callers without web users

src/main/java/org/jitsi/jigasi/util/Util.java
When there is a burst of answer/hangups (more than 20 at a time) we end up with:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1ed35d34 rejected from java.util.concurrent.ThreadPoolExecutor@41de9032[Running, pool size = 20, active threads = 20, queued tasks = 0, completed tasks = ...]
We change it to unbound queue for tasks, there cannot be unlimited answer/hangups. It is also used and for handling dial-in requests ... that is protected for bursts from the XMPP side.
=> fix: Handles burst of answer/hangup tasks.

pom.xml
ZRTTransformEngine is being initialized by default even when DEFAULT_ENCRYPTION=false is set for the account.
=> fix: Skips ZRTTransformEngine when encryption is disabled.

src/main/java/org/jitsi/jigasi/health/SipHealthPeriodicChecker.java
In the case of a temporary network issue a sip health check call can fail, but will not be hanged up and that leads to leaking threads and objects.
=> fix: Make sure we always hangup sip health calls.

src/main/java/org/jitsi/jigasi/stats/Statistics.java
~~This commit exposes a new metric (called "stress_level") that can be
used to determined the load factor of a Jigasi instance. It is currently
based on the number of concurrent conferences with a default normalizing
constant of 450. This constant needs to be fine tuned based on the
specific instance type that Jigasi is running and it needs to represent
the max number of conferences that Jigasi can handle correctly on the
specific instance type (i.e. if Jigasi has more conferences it is
overloaded and it may experience abnormal operation).~~
This commit exposes a new metric (called "stress_level") that can be
used to determined the load factor of a Jigasi instance. It is currently
based on the existing autoscaling rules that we have and we'll tweak
it in the near future to something that …
=> feat: Exposes the "stress_level" metric.

src/main/java/org/jitsi/jigasi/SipGatewaySession.java
initStatsService was failing to find the correct callstats config as it was executed before we receive the sip headers via onJoinJitsiMeetRequest. We need to domain (domain_base) to be able to match and find the correct xmpp account and callstats settings.
=> fix: Fixes callstats reporting on the sip leg of the call.

src/main/java/org/jitsi/jigasi/SipGatewaySession.java
Without rewriting the ssrc jigasi pass through the one incoming from the sip provider and browsers doing ssrc validation will fail to play the audio (Safari, Firefox and chrome with unified plan) as we had announced another ssrc earlier when setting up the call.
=> fix: Fixes ssrc rewrite when creating outgoing calls.

pom.xml
Notably, this transitively pulls in log4j 2.15.0.
=> Bump jitsi-stats.

src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/AudioModeration.java, src/main/java/org/jitsi/jigasi/CallContext.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/stats/StatsHandler.java, src/main/java/org/jitsi/jigasi/util/Util.java, src/main/java/org/jitsi/jigasi/xmpp/CallControl.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Adds an option for new sip header to pass not only the domain, but and the tenant.
Adds muc prefix to cover cases when docker is used and the muc component address is `muc.meet.jitsi`.
Make sure we use the muc jid to construct any jid we will be using, for joining, for querying jicofo or hosts for av moderation or lobby.
=> Tenant header option

src/main/java/org/jitsi/jigasi/CallContext.java, src/main/java/org/jitsi/jigasi/JvbConference.java
Normally the host for bosh is coming as the param domain_base, but this option helps to override it for specified domains.
org.jitsi.jigasi.BOSH_HOST_OVERRIDE=my.domain.com=other.domain.net,hop.domain.com=second.domain.net
=> feat: Adds option to override the bosh host that is used.

src/main/java/org/jitsi/jigasi/CallManager.java, src/main/java/org/jitsi/jigasi/util/Util.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Making the call manager thread pull to grow from 1 to 1000. If we reach 1000 means there are a lot of blocked calls or there is an enormous burst of calls, in any way this jigasi will become unhealthy due to the large number of threads.
We have been seeing when calling answer to a call to get blocked that will prevent of spinning new threads to handle future answer calls and no media is being established.
Agent stays in running forever ¯\_(ツ)_/¯
"jigasi-callManagerpool-26-thread-1" #269 daemon prio=5 os_prio=0 tid=0x00007fad1c07e000 nid=0x2666 in Object.wait() [0x00007facf3abd000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at net.java.sip.communicator.impl.protocol.jabber.IceUdpTransportManager.wrapupConnectivityEstablishment(IceUdpTra …
=> fix: Blocking future answer calls if on answer is blocked.

debian/control
Allows running it with java17. Drops unused dependency.
=> feat: Sets jre11 as minimum required.

pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java
2022-05-24 06:06:26.858 WARNING: [6379] org.jivesoftware.smack.util.PacketParserUtils.parsePresence: Failed to parse extension element in Presence stanza: PresenceBuilder(from='.....
java.lang.NullPointerException
at org.jivesoftware.smack.packet.StanzaBuilder.addExtension(StanzaBuilder.java:160)
at org.jivesoftware.smack.util.PacketParserUtils.parsePresence(PacketParserUtils.java:478)
at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:115)
at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1454)
at org.jivesoftware.smack.bosh.XMPPBOSHConnection.access$1500(XMPPBOSHConnection.java:69)
at org.jivesoftware.smack.bosh.XMPPBOSHConnection$BOSHPacketReader.responseReceived(XMPPBOSHConnection.java:520)
at …
=> feat: Updates jitsi-xmpp extensions, fixes NPE.

pom.xml, src/main/java/org/jitsi/jigasi/Main.java
Prevents bosh from blocking smack reactor which will result all smack communications to be blocked.
https://discourse.igniterealtime.org/t/bosh-connection-blocks-all-smackreactor-threads/91719
=> feat: Updates smack.

pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java
We have seen missing audio-mute support in jicofo as it doesn't update disco info after presence changes the advertised capabilities hash.
=> feat: Set features as early as possible to avoid updating presence.

src/main/java/org/jitsi/jigasi/JvbConference.java
They are always required and the signaled features are ignored.
=> Remove the rtcpmux and bundle features.

.gitignore, src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java
This PR fixes repeated subtitles in VOSK transcription results.
The issue came from non-persistent UUIDs when sending the transcription results to Jitsi.
Creating a new UUID when the results are not `partial` fixes the issue.
Please let me know if I can add/edit anything to this PR.
=> fix: repeated strings in VOSK transcription results

README.md, jigasi-home/sip-communicator.properties, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/Participant.java, src/main/java/org/jitsi/jigasi/transcription/TranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java
This PR implements language routing capabilities for the VOSK transcription service.
A VOSK model only allows one language, so each VOSK service can only transcribe one language. With language routing, we can assign a language to a websocket URL, which points to the correct VOSK container as shown in the image below:
Please let me know if I can provide any additional information/modifications.
=> feat: add VOSK routing

src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java
This PR fixes a missing `return` statement.
Without it, the code below would be executed and the JSON serializer would try to parse a non-JSON string, causing an error.
=> fix: missing return

README.md
When LibreTranslate support and VOSK multi-instance routing both merged into the master, the VOSK language routing configuration got placed under LibreTranslate in the readme file. This PR re-arranges the newly added text in the correct order.
=> fixed the vosk configuration guide

src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
In older format the whole jid is sent and we were extracting the resource, but the new one sends just the resource. The change broke transcriptions wher we need to match audio stream to participant.
=> feat: Handles source-add with endpoint id.

pom.xml, src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
This allows sorting of the resulted messages based on the id, which is created when that message/phrase started.
=> feat: Use time-based uuid for transcription id.

pom.xml, src/main/java/org/jitsi/jigasi/lobby/Lobby.java
Sometimes LOCAL_USER_LEFT is fired before room destroyed and sip call is not hangup waiting for xmpp to reconnect the jvb call. Race between stanza listeners, which will be the first to handle the presence stanza. After this change only destroy room event will be fired.
=> fix: Fixes handling of destroying the room.

src/main/java/org/jitsi/jigasi/transcription/Participant.java
This PR fixes the issue mentioned in the thread below:
https://community.jitsi.org/t/jigasi-randomly-starts-sending-raw-vosk-json-response-as-subtitles/117831
The problem came from lost websocket connection between jigasi and the VOSK transcription service.
Before the change, a participant whose audio should be transcribed switches to the single request mode when the session is prematurely ended. The PR allows Jigasi to check whether streaming is supported by the transcription service, and if it is the case, re-establish the streaming session.
=> fix: re-establish connection with transcription service if session is prematurely ended

pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/lobby/Lobby.java, src/main/java/org/jitsi/jigasi/sounds/SoundNotificationManager.java, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
Make sure we do not send and/or wait for responses in the smack threads.
=> feat: Offload xmpp/smack processing threads.

jigasi-home/sip-communicator.properties, pom.xml, src/main/java/org/jitsi/jigasi/JvbConference.java
Updates to latest desktop lib dependency to fix ALWAYS_TRUST_MODE_ENABLED.
=> feat: Adds an option to randomize user-id used when client logins.

src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/RemotePublisherTranscriptionHandler.java, src/main/java/org/jitsi/jigasi/transcription/action/ActionServicesHandler.java
In commit 89cb8987, "feat: Changes transcript msgs to have timestamp as milliseconds," there are two issues:
1. This didn't change the JSON output for all transcript messages. For instance, START and END event messages continued to have their timestamps encoded as an ISO-8601 string.
2. Arguably, most JSON parsers would expect epoch milliseconds encoded as a number rather than a string. 
This humble PR addresses both of those issues by ensuring all transcript JSON messages have their timestamps encoded as a JSON number (milliseconds since epoch).
=> Timestamp improvements

pom.xml, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
- chore: Update jitsi-xmpp-extensions.
- Avoid using XmlStringBuilder.toString.
=> Avoid using XmlStringBuilder.toString()

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
Slow down events internally in the transcriber, so we give time for the service to return any pending transcriptions. We also wait for all leave processing to finish before transcriber leaves the room, so any sent transcriptions to be processed.
=> feat(transcription): Slow down leaving participants.

src/main/java/org/jitsi/jigasi/transcription/Participant.java
We have been working on the ability to change the transcription language dynamically from the web UI: a participant modifying their local settings (Three dots -> Settings -> General -> Language) would be able to start speaking in another language and still get an accurate transcription.
We are testing this functionality with local Vosk instances and it's working fine, however we had to make a very small modification to the code: without this one line change, Jigasi starts creating a lot of new WebSockets and eventually exhausts all resources. This is because in `sendRequest()` we never keep track of newly created `TranscriptionService.StreamingRecognitionSession`s.
While we understand that changing transcription language dynamically is not something that is natively supported (yet) by …
=> fix: streaming session handling should account for dynamically changed transcription language

debian/links, pom.xml
Drops a link that is no longer needed, the source file has been removed.
Also updates bouncycastle from 1.75 to 1.77.
=> feat: Updates to latest libjitsi, opus 1.5.2.

src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java, src/main/java/org/jitsi/jigasi/JvbConference.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java, src/main/java/org/jitsi/jigasi/sip/SipInfoJsonProtocol.java
=> feat(visitors): Notifies for not live call via sip info msg.

script/reconfigure_xmpp.sh
=> fix(reconfigure_xmpp): correctly provide password unencoded via REST

README.md, src/main/java/org/jitsi/jigasi/TranscriptionGateway.java
=> Refactor transcriber selection

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java, src/main/java/org/jitsi/jigasi/transcription/Participant.java, src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
=> Flush the participant's audio buffer on mute

src/main/java/org/jitsi/jigasi/stats/Statistics.java, src/main/java/org/jitsi/jigasi/transcription/Participant.java
=> Add metrics for the amount of audio sent to each transcriber

src/main/java/org/jitsi/jigasi/JvbConference.java
=> feat: Handles demote request.

src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java
Fixes:
2024-10-26 19:23:56.896 INFO: [254] WhisperWebsocket.disconnectParticipant#353: All participants have left, disconnecting from Whisper transcription server. 2024-10-26 19:23:56.897 SEVERE: [254] net.java.sip.communicator.util.UtilActivator.uncaughtException: An uncaught exception occurred in thread=Thread[jigasi-whisper-wspool-7-thread-2,5,main], and message was: Cannot invoke "org.eclipse.jetty.websocket.api.Session.getRemote()" because "this.wsSession" is null java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.websocket.api.Session.getRemote()" because "this.wsSession" is null
at org.jitsi.jigasi.transcription.WhisperWebsocket.disconnectParticipant(WhisperWebsocket.java:354)
at org.jitsi.jigasi.transcription.WhisperConnectionPool.endInternal(WhisperConnectionPool.jav …
=> fix(whisper): Fixes possible NPE.

src/main/java/org/jitsi/jigasi/stats/Statistics.java, src/main/java/org/jitsi/jigasi/transcription/WhisperConnectionPool.java, src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java
Executes stop and connect in a different from the websocket messages thread as recommended in jetty docs.
=> fix(whisper): Reconnects on socket closed while operating.

src/main/java/org/jitsi/jigasi/transcription/oracle/OracleRealtimeClient.java
=> fix(transcription): Stop websocket in new thread as recommended.

src/main/java/org/jitsi/jigasi/transcription/TranslationManager.java, src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java
=> Process translations and xmpp sending of transcription in separate threads

pom.xml, src/main/java/org/jitsi/jigasi/AudioModeration.java, src/main/java/org/jitsi/jigasi/TranscriptionGateway.java, src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java, src/main/java/org/jitsi/jigasi/transcription/RemotePublisherTranscriptionHandler.java, src/main/java/org/jitsi/jigasi/transcription/Util.java, src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java, src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java, src/main/java/org/jitsi/jigasi/transcription/action/ActionServicesHandler.java, src/main/java/org/jitsi/jigasi/visitor/WebsocketClient.java
Drop org.json and use the one common in other dependencies.
=> fix: Drops duplicate json dependency.

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
Fixes ArrayIndexOutOfBoundsException when participant is audio and video muted.
=> fix: Detection of muting, checks only audio source.

pom.xml, src/main/java/org/jitsi/jigasi/JigasiBundleActivator.java, src/main/java/org/jitsi/jigasi/sounds/SoundNotificationManager.java
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/109
=> feat: Adds notification for conference audio recordings.

src/main/java/org/jitsi/jigasi/JvbConference.java
Change replace to replaceAll
See https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#replaceAll(java.lang.String,java.lang.String)
CLA (https://jitsi.org/icla for individuals) already signed
=> fix: clean up XMPP resource id

pom.xml, src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java
=> chore: Bump jicoco, jitsi-xmpp-extensions, smack.

src/main/java/org/jitsi/jigasi/AudioModeration.java, src/main/java/org/jitsi/jigasi/SipCallTransformer.java, src/main/java/org/jitsi/jigasi/SipGatewaySession.java
This works only in the case when a streams are being forwarded (no transcoding).
=> fix: Fixes mute to stop forwarding stream.
