jigasi-home/sip-communicator.properties
pom.xml
src/main/java/org/jitsi/jigasi/JvbConference.java
src/test/java/net/java/sip/communicator/service/protocol/mock/MockJitsiMeetTools.java

In order to enable set org.jitsi.jigasi.xmpp.acc.BOSH_URL_PATTERN
(see jigasi-home/sip-communicator.properties for example)

Add BOSH support

---

pom.xml
src/main/java/org/jitsi/jigasi/AbstractGatewaySession.java
src/main/java/org/jitsi/jigasi/JvbConference.java
src/main/java/org/jitsi/jigasi/SipGatewaySession.java
src/main/java/org/jitsi/jigasi/TranscriptionGateway.java
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/test/java/net/java/sip/communicator/service/protocol/mock/muc/MockRoomMember.java

relies on [PR 55](https://github.com/jitsi/jigasi/pull/55) in jigasi 
relies on changes in [jitsi-protocol and jitsi-protocol-jabber](https://github.com/jitsi/jitsi/tree/transcription)

Add a TranscriptionGateway and TranscriptionGatewaySession

---

src/main/java/org/jitsi/jigasi/JigasiBundleActivator.java
src/main/java/org/jitsi/jigasi/xmpp/CallControl.java
src/main/java/org/jitsi/jigasi/xmpp/CallControlComponent.java
src/main/java/org/jitsi/jigasi/xmpp/CallControlMucActivator.java

relies on [PR 56](https://github.com/jitsi/jigasi/pull/56)
When the DialIQ's uri is "transcribe:", a transcriber will join the room, otherwise a sip connection joins the room

added a TranscriptionGateway OSGI service

---

src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptionService.java

warn in log and sends a message to the chat before leaving immediately
wait for merge until I tested it on a computer with the credentials set

more gracefully fail when Google Cloud credentials are not set correctly

---

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java

Includes: 
add constants for maximum alternatives interim results and single utterance
remove overlapping sessions
create new session whenever a final result comes in
close session whenever there is an error or a final result

Refactor GoogleCloudTranscriptionService to better deal with 1 minute StreamingRecognize restriction

---

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptionResult.java

necessary for JSON transcripthandler pr

add an UUID, interim result and language tag field to TranscriptionResult

---

src/main/java/org/jitsi/jigasi/TranscriptionGateway.java
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/LocalTxtTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/SpeechEvent.java
src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
src/main/java/org/jitsi/jigasi/transcription/Transcript.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptEvent.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptHandler.java

Relies on #70 
Example chat message:
```
{
"transcript":[
{
"confidence":0.9876291155815125,
"text":"how are you"
}
],
"name":"Nik",
"is_interim":false,
"language":"en-US",
"message_id":"ab93f8d1-4120-4296-8120-7b4f80db0e22",
"id":"c02d8481",
"event":"SPEECH",
"timestamp":"2017-08-07T14:26:23.637Z"
}
```
Example complete transcript:
```
{
"room_name": "test123@conference.nik.jitsi.net",
"start_time": "2017-08-07T14:31:55.110Z",
"initial_participants": [
"Nik"
],
"end_time": "2017-08-07T14:32:21.333Z",
"events": [
{
"transcript": [
{
"confidence": 0.932471752166748,
"text": "hey how are you"
}
],
"name": "Nik",
"is_interim": false,
"language": "en-US",
"message_id": "a235ba29-a966-4e8b-a9fa-95b034fbffac",
"id": "c02d8481",
"event": "SPEECH",
"timestamp": "2017-08-07T14:32:05.848Z"
},
{ …
```

implement saving and sending TranscriptResult information in JSON

---

jigasi-home/sip-communicator.properties
script/example_handle_transcript_directory.sh
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java
src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/LocalTxtTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptPublisher.java

First in a series of PR's to implement the storage of audio recordings

Implement unique directory per conference, recording mix and executing scripts

---

debian/control
debian/jigasi.service
debian/postinst
debian/rules
pom.xml
script/collect-dump-logs.sh
script/graceful_shutdown.sh
src/main/java/org/jitsi/jigasi/CallManager.java
src/main/java/org/jitsi/jigasi/JvbConference.java

I also want to add to this PR https://github.com/jitsi/jitsi/pull/566 and https://github.com/jitsi/libjitsi/pull/464. So pom needs updating after the other two are merged.

Cleanup calls and adds systemd

---

src/main/java/org/jitsi/jigasi/TranscriptionGateway.java
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java
src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java
src/main/java/org/jitsi/jigasi/transcription/Participant.java
src/main/java/org/jitsi/jigasi/transcription/Transcriber.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptionService.java

Fixes some error logs to go to logger.
Added some extra parameters to the API.
Removed a duplicate DD code.

Adds option to plugin custom transcription service.

---

src/main/java/org/jitsi/jigasi/health/Health.java
src/main/java/org/jitsi/jigasi/rest/HandlerImpl.java

Will check is there a gateway that is no ready, in case of sip it will
check whether provider is registered.

Improves health checking.

---

pom.xml

Bumps ice4j(0b052e8) and libjitsi(3bbdbcf).
Changes the property change listener to strong reference. Removes
"Cannot find method ..." error message.

Fixes randomly failing dtls on call setup.

---

pom.xml
src/main/java/org/jitsi/jigasi/stats/CallPeriodicRunnable.java

Adapts to changes in jitsi/jitsi-stats#8

Adapts to changes in jitsi-stats.

---

pom.xml

Fixes a possible concurrency issue when translating a call in jigasi and the xmpp and sip call end up with different translators.

Synchronizes translator creation/disposal.

---

pom.xml

The logic is simplified and proper synchronized, using 
https://github.com/jitsi/jitsi/commit/41a063d2465ef28f9ead09f0756b23c1219d52ca

Reverts 0943530b and updates to latest reconnect logic updates.

---

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java

Stabilize google transcriptions

---

jigasi.sh

Partially reverts changes in the script from de88afd.

Fixes sh start script.

---

pom.xml

Bringing configuration for received buffer sizes.

Bumps libjitsi and jitsi-utils.

---

pom.xml

"qtp802921335-29":
at net.java.sip.communicator.plugin.reconnectplugin.PPReconnectWrapper.registrationStateChanged(PPReconnectWrapper.java:148)
- waiting to lock <0x000000070068f518> (a java.lang.Object)
at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.unregisterInternal(ProtocolProviderServiceJabberImpl.java:1574)
- locked <0x0000000700267760> (a java.lang.Object)
at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.unregister(ProtocolProviderServiceJabberImpl.java:1536)
at org.jitsi.jigasi.xmpp.CallControlMucActivator.removeCallControlMucAccount(CallControlMucActivator.java:49 …

Updates jitsi-desktop deps, fixes deadlock.

---

src/main/java/org/jitsi/jigasi/transcription/GoogleCloudTranscriptionService.java

Counts the Google Speech API requests and reports to the data dog client under 'google_cloud_speech_requests'.

feat(data dog): add google_cloud_speech_requests

---

jigasi-home/sip-communicator.properties
pom.xml
src/main/java/org/jitsi/jigasi/transcription/Participant.java
src/main/java/org/jitsi/jigasi/transcription/SilenceFilter.java
src/main/java/org/jitsi/jigasi/transcription/Transcriber.java

Rebased version of https://github.com/jitsi/jigasi/pull/144 with fixes to native lib loading in https://github.com/jitsi/jitsi-webrtc-vad-wrapper/commit/59923d3f9ecf8059f9fe61c17d420f5df538ca08

add ability to filter out speechless audio based on WebRTCVAD library

---

jigasi-home/sip-communicator.properties
src/main/java/org/jitsi/jigasi/JvbConference.java

make max occupants limit notification configurable

---

pom.xml
src/main/java/org/jitsi/jigasi/CallManager.java
src/main/java/org/jitsi/jigasi/SipGatewaySession.java
src/main/java/org/jitsi/jigasi/SoundNotificationManager.java
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/health/Health.java
src/main/java/org/jitsi/jigasi/rest/HandlerImpl.java

Uses a dynamic pool of threads and if max number is reached we mark
jigasi as unhealthy and fail calls.

fix: Changes CallManager to detect unhealthy state.

---

jigasi-home/sip-communicator.properties
pom.xml
src/main/java/org/jitsi/jigasi/JvbConference.java
src/main/java/org/jitsi/jigasi/SipGatewaySession.java
src/main/java/org/jitsi/jigasi/stats/CallPeriodicRunnable.java
src/main/java/org/jitsi/jigasi/stats/StatsHandler.java
src/test/java/org/jitsi/jigasi/CallsHandlingTest.java

Depends on https://github.com/jitsi/jitsi-stats/pull/10

feat: Updates jitsi-stats introducing SiteID.

---

src/main/java/org/jitsi/jigasi/stats/StatsHandler.java

The call change listener was added only for the first call that does the initialization of the stats service for this app id.

fix: Fixes sending stats to callstats.

---

README.md
jigasi-home/sip-communicator.properties
pom.xml
src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java

This is an initial attempt to implement speech recognition with the open source[ Vosk transcription server](https://github.com/alphacep/vosk-server). The server supports several languages and runs without internet. Installation is done with a simple docker command.
Everything seems in place, just need to test it properly.

Vosk speech recognition transcription service

---

src/main/java/org/jitsi/jigasi/CallContext.java
src/main/java/org/jitsi/jigasi/SipGatewaySession.java

We needed tokens to be passed to incoming calls and the attached PR is a quick hack to add the feature. A review is appreciated. Thanks.

Pass token to incoming call

---

src/main/java/org/jitsi/jigasi/transcription/VoskTranscriptionService.java

as per this discussion here:
https://community.jitsi.org/t/jigasi-transcription-with-vosk-repeated-lines/91573/13

fix duplicate strings with Vosk

---

pom.xml
src/main/java/org/jitsi/jigasi/JvbConference.java

Also clears MediaStream Stats.

fix: Handles participant left as sourceRemove.

---

pom.xml

Adding duplicate formats in a static Vector.
A static table with ssrc was accumulating objects.

Fixes several memory leaks.

---

pom.xml
src/main/java/org/jitsi/jigasi/health/SipHealthPeriodicChecker.java

Depends on https://github.com/jitsi/jitsi/pull/757 and needs an update in pom after having a build of it.

feat: Prints session-info if available on health check failure.

---

src/main/java/org/jitsi/jigasi/transcription/Participant.java

More info: https://github.com/jitsi/jigasi/commit/8d5b46be7a4d624d289a2983da4460562de31ab1

fix: Another fix buffer clearing when compiled with java11.

---

pom.xml

use this changes: https://github.com/jitsi/libjitsi/pull/562

fix: handle dtmf events correctly

---

README.md

I've omitted to update the readme file in my [pull request to integrate LibreTranslate service](https://github.com/jitsi/jigasi/pull/455) in Jigasi.
So here is the update that should have been included in the previous PR. 😁

update readme.md for libretranslate configuration

---

pom.xml

Adds to options where you can force leaving room and re-register on TLS socket close.

feat: Updated jitsi-desktop dependency to latest.

---

src/main/java/org/jitsi/jigasi/SipGatewaySession.java
src/main/java/org/jitsi/jigasi/stats/Statistics.java

Count all occurrences when we have a pause in receiving media.

feat: New dropped media stat.

---

pom.xml

Adds Allow header to 200 OK responses of invite requests.

feat: Updates desktop-libs dependency.

---

pom.xml
src/main/java/org/jitsi/jigasi/metrics/JigasiMetricsContainer.java
src/main/java/org/jitsi/jigasi/rest/AbstractJettyBundleActivator.java
src/main/java/org/jitsi/jigasi/rest/MetricsHandler.java
src/main/java/org/jitsi/jigasi/stats/Statistics.java

- chore: Update jicoco.
- feat: Port some metrics to prometheus.
- chore: Bump jetty.
- feat: Add a /metrics endpoint for prometheus.
- feat: Port most stats to metrics.

feat: Add a prometheus /metrics endpoint.

---

jigasi-home/sip-communicator.properties
pom.xml
src/main/java/org/jitsi/jigasi/AudioModeration.java
src/main/java/org/jitsi/jigasi/JigasiBundleActivator.java
src/main/java/org/jitsi/jigasi/JvbConference.java
src/main/java/org/jitsi/jigasi/SipGatewaySession.java
src/main/java/org/jitsi/jigasi/sip/SipInfoJsonProtocol.java
src/main/java/org/jitsi/jigasi/xmpp/extensions/RaiseHandExtension.java
src/main/java/org/jitsi/jigasi/xmpp/extensions/VisitorsPromotionResponseExtension.java

A basic implementation where jigasi joins as visitor. Cannot raise a hand.

Visitors implementation

---

script/reconfigure_xmpp.sh

fix(reconfigure_xmpp): curl headers missing content type

---

script/graceful_shutdown.sh

feat(graceful_shutdown): detect pid via ps if not written into /var/run

---

src/main/java/org/jitsi/jigasi/transcription/Util.java

fix(transcriptions): When posting json make sure it is UTF-8.

---

pom.xml

Fixes jitsi/docker-jitsi-meet#1954.

fix: Fixes disabling of packet logger.

---

src/main/java/org/jitsi/jigasi/JvbConference.java
src/main/java/org/jitsi/jigasi/TranscriptionGatewaySession.java
src/main/java/org/jitsi/jigasi/lobby/Lobby.java
src/main/java/org/jitsi/jigasi/transcription/AbstractTranscriptPublisher.java
src/main/java/org/jitsi/jigasi/transcription/LocalJsonTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/LocalTxtTranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/RemotePublisherTranscriptionHandler.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptHandler.java
src/main/java/org/jitsi/jigasi/transcription/TranscriptionResultPublisher.java

fix(transcription): Sends transcription over xmpp in separate thread.

---

src/main/java/org/jitsi/jigasi/JvbConference.java

fix: Fixes wrong check for room.

---

src/main/java/org/jitsi/jigasi/transcription/OracleTranscriptionService.java
src/main/java/org/jitsi/jigasi/transcription/WhisperTranscriptionService.java

Set oracle language code

---

README.md
src/main/java/org/jitsi/jigasi/transcription/OracleTranscriptionService.java

Add OCI transcriber silence threshold properties

---

src/main/java/org/jitsi/jigasi/JvbConference.java

feat: Adds stats-id to presence.

---

src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java

fix(whisper): Make authorization optional.

---

src/main/java/org/jitsi/jigasi/transcription/WhisperWebsocket.java

Whisper reconnect

---

pom.xml

chore: Bump xmpp-extensions, jicoco.

---

pom.xml

chore: Bump smack, jitsi-xmpp-extensions, jicoco.
